coffe_shop:
    resource: "@CoffeShopBundle/Resources/config/routing.yml"
    prefix:   /

placement:
    resource: "@PlacementBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation