services:
    infrastructure.persistence.student.repository:
        class: PlacementBundle\Infrastructure\Persistence\Doctrine\DoctrineStudentRepository
        factory: ["@doctrine", getRepository]
        public: false
        arguments: ["PlacementBundle:Students"]

    domain.student.service:
        class: PlacementBundle\Domain\Student\StudentService
        public: false
        arguments: ["@infrastructure.persistence.student.repository"]

    application.studentBybestFriendsHigherSalary_usecase:
        class: PlacementBundle\Application\GetAvailableStudentsByBestFriendsHigherSalaryUseCase
        arguments: ["@domain.student.service"]
