services:
    infrastructure.persistence.coffee.repository:
        class: CoffeeShopBundle\Infrastructure\Persistence\InMemory\InMemoryCoffeeRepository

    domain.coffee.service:
        class: CoffeeShopBundle\Domain\Coffee\CoffeeService
        public: false
        arguments: ["@infrastructure.persistence.coffee.repository"]

    application.coffees_menu_use_case:
        class: CoffeeShopBundle\Application\GetAvailableCoffeesMenuUseCase
        arguments: ["@domain.coffee.service"]